### ISSUE TITLE
Issue after updating assets

### ISSUE THREAD

**Issue by msurkhan** [nayaabkhan/rpi1b-retroarch#2]
Hi nayaab, first of all thank you for the guide it was nice to follow and I made it to the end as a new user of pi. I had updated asset after launching retroarch and the pi just keeps running through codes and failing, it says 

eglCreateImageKHR: failed to create image for buffer (nil) target 12474 error 0 x 300c

**Comment by msurkhan** [comment]
Any way to get around the error?

**Comment by nayaabkhan** [comment]
I didn't face this error during my setup, so I don't know how to get around it. Although, as it is EGL related you could play around with any EGL-related flags.

**Comment by msurkhan** [comment]
No problem, I think assets are not so important as the rest of the system should work without them

**Comment by msurkhan** [comment]
Thank you
